### PR TITLE
Alternative proposal for dual-funding `tx_signatures` ordering

### PR DESCRIPTION
**Pull request by t-bast**
The peer that sends `tx_signatures` first is taking a risk when they are contributing to the channel funding: the other peer may never send their `tx_signatures`, and the signer will need to double-spend themselves to ensure that their funds are not locked.

The accepting node is more at risk here, as they don't choose who tries to open channels to them, whereas an opening node who detects a malicious accepting node can just go somewhere else to open a channel.

Thus by default, the opener should send their `tx_signatures` first, unless they explicitly request the accepting node to go first because they are trying to coordinate multiparty tx construction.

In my opinion, there are only two cases where the accepting node would contribute to a channel being opened to them:

- when they are using liquidity ads and are getting paid for it: in that case, they may be willing to take a risk and sign first (with policies to restrict how often / how much they are risking)
- when the opening node is in some kind of pre-configured whitelist of nodes the accepting node is interested in, in which case the node operator has manually selected those nodes and is probably willing to take the risk (at least once)

Credits to @morehouse who laid this out in https://github.com/lightning/bolts/pull/851#discussion_r997537630

@morehouse @niftynei let me know what you think. I'm not convinced that this is the right way, but at least it's an alternative to consider.

NB: this builds on top of #7, please only look at the last commit

### CODE REVIEW

**Review by morehouse — APPROVED** [review]
Works for me!

**Comment by niftynei** [comment]
I think I've come around to being ok with a flag for "peer must be first" flag. The griefing usecase for a large LSP is a "real and present" danger as you've pointed out. While we might be able to mitigate this in the future with PODLEs, right now it's a good thing to have so we should add it.

I would suggest that we leave the "biggest amount goes last" as the default (as this nominally helps with batched/multiparty opens... even though I haven't coded it up yet, currently we send sigs as soon as we have them). What do you think @t-bast ?

Also apologies for moving the discussion, I can't figure out where the last comments ended up...

**Comment by t-bast** [comment]
> I would suggest that we leave the "biggest amount goes last" as the default (as this nominally helps with batched/multiparty opens... even though I haven't coded it up yet, currently we send sigs as soon as we have them). What do you think @t-bast ?

Just to make sure I understand this correctly, instead of "opener goes first but can request the other peer to start", you would like to have:

- If `remote_tx_signatures_first` is not included, "smallest amount contributed signs first"
- Either the opening node or the accepting node may send `remote_tx_signatures_first` (respectively in `open_channel2` or `accept_channel2`) to override that default ordering
- If the opening node sent `remote_tx_signatures_first`, the accepting node cannot send it and must send an `error` if they don't want to sign first

I believe this is worse than "opener goes first but can request the other peer to start", because in practice what will happen is that liquidity providers (accepters) will **always** set `remote_tx_signatures_first` to protect themselves by default (that's the most rational choice to maximize the yield on their liquidity). This means that opening nodes will have to send `remote_tx_signatures_first` whenever they want to do batching, and that the default ordering of  "smallest amount contributed signs first" will actually never be used, so why even specify (and implement) it? That only adds unnecessary complexity, doesn't it?

> this nominally helps with batched/multiparty opens

Why does it help though? If you're batching you just have to signal `remote_tx_signatures_first` and then you know that the batching will just work.

> Also apologies for moving the discussion, I can't figure out where the last comments ended up...

That's what happens when your PRs are too popular, too many people are interested and make great comments on it :laughing:

**Comment by morehouse** [comment]
> I would suggest that we leave the "biggest amount goes last" as the default (as this nominally helps with batched/multiparty opens... even though I haven't coded it up yet, currently we send sigs as soon as we have them). What do you think @t-bast ?

Leaving the naive dual-funding user open to DoS seems like a poor default.

I agree with @t-bast, and regardless of the "default" in the spec, for LND I intend to implement `remote_tx_signatures_first` as default for acceptors.

**Comment by t-bast** [comment]
I don't think this change is useful anymore, as I think the strategy outlined [here](https://github.com/lightning/bolts/pull/851#issuecomment-1323337101) gets rid of the griefing attack entirely with close to no downside. I'll close this PR soon unless we find an issue with the anti-griefing strategy.

**Pull request closed without merging**
